"""Generated compatibility map: legacy Termix (<=2.8) SDK paths -> Termix 2.9 routes.

Termix 2.9 moved host features into plugins served under /plugin-api/<id>, renamed
several routes, and moved host status to /host/status. The generated SDK methods
(and every MCP tool built on them) still call the old paths; rewrite_path() maps
them back onto the 2.9 surface at request time. Regenerate alongside the spec.
"""

from __future__ import annotations

import re

_ENTRIES = [
    ('DELETE', re.compile('^/docker/containers/(?P<sessionId>[^/]+)/(?P<containerId>[^/]+)/remove$'), '/plugin-api/docker/containers/{sessionId}/{containerId}/remove', ('sessionId', 'containerId')),
    ('GET', re.compile('^/docker/containers/(?P<sessionId>[^/]+)/(?P<containerId>[^/]+)/stats$'), '/plugin-api/docker/containers/{sessionId}/{containerId}/stats', ('sessionId', 'containerId')),
    ('GET', re.compile('^/docker/containers/(?P<sessionId>[^/]+)/(?P<containerId>[^/]+)/logs$'), '/plugin-api/docker/containers/{sessionId}/{containerId}/logs', ('sessionId', 'containerId')),
    ('POST', re.compile('^/ssh/file_manager/ssh/trash/(?P<id>[^/]+)/restore$'), '/plugin-api/file-manager/trash/{id}/restore', ('id',)),
    ('GET', re.compile('^/docker/containers/(?P<sessionId>[^/]+)/(?P<containerId>[^/]+)$'), '/plugin-api/docker/containers/{sessionId}/{containerId}', ('sessionId', 'containerId')),
    ('POST', re.compile('^/ssh/file_manager/ssh/transferCleanup/(?P<transferId>[^/]+)$'), '/plugin-api/file-manager/transferCleanup/{transferId}', ('transferId',)),
    ('GET', re.compile('^/ssh/file_manager/ssh/transferStatus/(?P<transferId>[^/]+)$'), '/plugin-api/file-manager/transferStatus/{transferId}', ('transferId',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/transferCancel/(?P<transferId>[^/]+)$'), '/plugin-api/file-manager/transferCancel/{transferId}', ('transferId',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/transferRetry/(?P<transferId>[^/]+)$'), '/plugin-api/file-manager/transferRetry/{transferId}', ('transferId',)),
    ('DELETE', re.compile('^/fleets/(?P<id>[^/]+)/members/(?P<hostId>[^/]+)$'), '/plugin-api/fleets/{id}/members/{hostId}', ('id', 'hostId')),
    ('DELETE', re.compile('^/ssh/file_manager/ssh/trash/(?P<id>[^/]+)$'), '/plugin-api/file-manager/trash/{id}', ('id',)),
    ('POST', re.compile('^/ai/proposals/(?P<id>[^/]+)/mark\\-run\\-in\\-terminal$'), '/plugin-api/ai/proposals/{id}/mark-run-in-terminal', ('id',)),
    ('GET', re.compile('^/session\\-sharing/host/(?P<hostId>[^/]+)/active$'), '/plugin-api/session-sharing/host/{hostId}/active', ('hostId',)),
    ('PUT', re.compile('^/snippets/folders/(?P<name>[^/]+)/metadata$'), '/plugin-api/snippets/folders/{name}/metadata', ('name',)),
    ('GET', re.compile('^/automations/runs/(?P<runId>[^/]+)/steps$'), '/plugin-api/automations/runs/{runId}/steps', ('runId',)),
    ('GET', re.compile('^/ssh/tunnel/status/(?P<tunnelName>[^/]+)$'), '/plugin-api/tunnels/status/{tunnelName}', ('tunnelName',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/transfer/pull$'), '/plugin-api/fleets/{id}/transfer/pull', ('id',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/transfer/push$'), '/plugin-api/fleets/{id}/transfer/push', ('id',)),
    ('POST', re.compile('^/ai/proposals/(?P<id>[^/]+)/reject$'), '/plugin-api/ai/proposals/{id}/reject', ('id',)),
    ('GET', re.compile('^/ai/providers/(?P<id>[^/]+)/models$'), '/plugin-api/ai/providers/{id}/models', ('id',)),
    ('POST', re.compile('^/ai/proposals/(?P<id>[^/]+)/apply$'), '/plugin-api/ai/proposals/{id}/apply', ('id',)),
    ('GET', re.compile('^/session\\-sharing/resolve/(?P<linkToken>[^/]+)$'), '/plugin-api/session-sharing/resolve/{linkToken}', ('linkToken',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/transferMethodPreview$'), '/plugin-api/file-manager/transferMethodPreview', ()),
    ('POST', re.compile('^/workspaces/(?P<id>[^/]+)/unset\\-default$'), '/plugin-api/workspaces/{id}/unset-default', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/downloadFileStream$'), '/plugin-api/file-manager/downloadFileStream', ()),
    ('POST', re.compile('^/session\\-sharing/(?P<shareId>[^/]+)/end$'), '/plugin-api/session-sharing/{shareId}/end', ('shareId',)),
    ('GET', re.compile('^/docker/containers/(?P<sessionId>[^/]+)$'), '/plugin-api/docker/containers/{sessionId}', ('sessionId',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/changePermissions$'), '/plugin-api/file-manager/changePermissions', ()),
    ('POST', re.compile('^/workspaces/(?P<id>[^/]+)/set\\-default$'), '/plugin-api/workspaces/{id}/set-default', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/uploadFileStream$'), '/plugin-api/file-manager/uploadFileStream', ()),
    ('PUT', re.compile('^/ssh/file_manager/ssh/trash\\-retention$'), '/plugin-api/file-manager/trash-retention', ()),
    ('POST', re.compile('^/automations/webhook/(?P<token>[^/]+)$'), '/plugin-api/automations/webhook/{token}', ('token',)),
    ('GET', re.compile('^/docker/validate/(?P<sessionId>[^/]+)$'), '/plugin-api/docker/validate/{sessionId}', ('sessionId',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/uploadFileChunk$'), '/plugin-api/file-manager/uploadFileChunk', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/identifySymlink$'), '/plugin-api/file-manager/identifySymlink', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/activeTransfers$'), '/plugin-api/file-manager/activeTransfers', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/extractArchive$'), '/plugin-api/file-manager/extractArchive', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/transferToHost$'), '/plugin-api/file-manager/transferToHost', ()),
    ('POST', re.compile('^/secret\\-sources/(?P<id>[^/]+)/test$'), '/plugin-api/secret-sources/{id}/test', ('id',)),
    ('GET', re.compile('^/session_logs/(?P<id>[^/]+)/content$'), '/plugin-api/session-recording/{id}/content', ('id',)),
    ('POST', re.compile('^/workspaces/(?P<id>[^/]+)/duplicate$'), '/plugin-api/workspaces/{id}/duplicate', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/connect\\-totp$'), '/plugin-api/file-manager/connect-totp', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/compressFiles$'), '/plugin-api/file-manager/compressFiles', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/downloadFile$'), '/plugin-api/file-manager/downloadFile', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/createFolder$'), '/plugin-api/file-manager/createFolder', ()),
    ('DELETE', re.compile('^/snippets/folders/(?P<name>[^/]+)$'), '/plugin-api/snippets/folders/{name}', ('name',)),
    ('PUT', re.compile('^/workspaces/(?P<id>[^/]+)/content$'), '/plugin-api/workspaces/{id}/content', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/executeFile$'), '/plugin-api/file-manager/executeFile', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/resolvePath$'), '/plugin-api/file-manager/resolvePath', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/uploadFile$'), '/plugin-api/file-manager/uploadFile', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/disconnect$'), '/plugin-api/file-manager/disconnect', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/createFile$'), '/plugin-api/file-manager/createFile', ()),
    ('DELETE', re.compile('^/ssh/file_manager/ssh/deleteItem$'), '/plugin-api/file-manager/deleteItem', ()),
    ('PUT', re.compile('^/ssh/file_manager/ssh/renameItem$'), '/plugin-api/file-manager/renameItem', ()),
    ('GET', re.compile('^/ai/conversations/(?P<id>[^/]+)$'), '/plugin-api/ai/conversations/{id}', ('id',)),
    ('DELETE', re.compile('^/ai/conversations/(?P<id>[^/]+)$'), '/plugin-api/ai/conversations/{id}', ('id',)),
    ('GET', re.compile('^/fleets/(?P<id>[^/]+)/inventory$'), '/plugin-api/fleets/{id}/inventory', ('id',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/inventory$'), '/plugin-api/fleets/{id}/inventory', ('id',)),
    ('POST', re.compile('^/workspaces/(?P<id>[^/]+)/apply$'), '/plugin-api/workspaces/{id}/apply', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/writeFile$'), '/plugin-api/file-manager/writeFile', ()),
    ('POST', re.compile('^/ssh/file_manager/ssh/keepalive$'), '/plugin-api/file-manager/keepalive', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/listFiles$'), '/plugin-api/file-manager/listFiles', ()),
    ('POST', re.compile('^/automations/(?P<id>[^/]+)/run$'), '/plugin-api/automations/{id}/run', ('id',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/packages$'), '/plugin-api/fleets/{id}/packages', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/copyItem$'), '/plugin-api/file-manager/copyItem', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/readFile$'), '/plugin-api/file-manager/readFile', ()),
    ('PUT', re.compile('^/ssh/file_manager/ssh/moveItem$'), '/plugin-api/file-manager/moveItem', ()),
    ('GET', re.compile('^/fleets/(?P<id>[^/]+)/members$'), '/plugin-api/fleets/{id}/members', ('id',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/members$'), '/plugin-api/fleets/{id}/members', ('id',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/execute$'), '/plugin-api/fleets/{id}/execute', ('id',)),
    ('PUT', re.compile('^/homepage/items/(?P<id>[^/]+)$'), '/plugin-api/homepage/items/{id}', ('id',)),
    ('DELETE', re.compile('^/homepage/items/(?P<id>[^/]+)$'), '/plugin-api/homepage/items/{id}', ('id',)),
    ('PUT', re.compile('^/vault/profiles/(?P<id>[^/]+)$'), '/plugin-api/vault/profiles/{id}', ('id',)),
    ('DELETE', re.compile('^/vault/profiles/(?P<id>[^/]+)$'), '/plugin-api/vault/profiles/{id}', ('id',)),
    ('POST', re.compile('^/ssh/file_manager/ssh/connect$'), '/plugin-api/file-manager/connect', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/status$'), '/plugin-api/file-manager/status', ()),
    ('PATCH', re.compile('^/ai/providers/(?P<id>[^/]+)$'), '/plugin-api/ai/providers/{id}', ('id',)),
    ('DELETE', re.compile('^/ai/providers/(?P<id>[^/]+)$'), '/plugin-api/ai/providers/{id}', ('id',)),
    ('POST', re.compile('^/fleets/(?P<id>[^/]+)/share$'), '/plugin-api/fleets/{id}/share', ('id',)),
    ('DELETE', re.compile('^/ssh/file_manager/ssh/trash$'), '/plugin-api/file-manager/trash', ()),
    ('GET', re.compile('^/ssh/file_manager/ssh/trash$'), '/plugin-api/file-manager/trash', ()),
    ('GET', re.compile('^/ssh/tunnel/status/stream$'), '/plugin-api/tunnels/status/stream', ()),
    ('DELETE', re.compile('^/session\\-sharing/(?P<shareId>[^/]+)$'), '/plugin-api/session-sharing/{shareId}', ('shareId',)),
    ('POST', re.compile('^/ssh/file_manager/sudo\\-password$'), '/plugin-api/file-manager/sudo-password', ()),
    ('PUT', re.compile('^/secret\\-sources/(?P<id>[^/]+)$'), '/plugin-api/secret-sources/{id}', ('id',)),
    ('DELETE', re.compile('^/secret\\-sources/(?P<id>[^/]+)$'), '/plugin-api/secret-sources/{id}', ('id',)),
    ('GET', re.compile('^/session_logs/(?P<id>[^/]+)$'), '/plugin-api/session-recording/{id}', ('id',)),
    ('DELETE', re.compile('^/session_logs/(?P<id>[^/]+)$'), '/plugin-api/session-recording/{id}', ('id',)),
    ('DELETE', re.compile('^/alert\\-rules/(?P<id>[^/]+)$'), '/plugin-api/alerts/rules/{id}', ('id',)),
    ('GET', re.compile('^/automations/(?P<id>[^/]+)$'), '/plugin-api/automations/{id}', ('id',)),
    ('PUT', re.compile('^/automations/(?P<id>[^/]+)$'), '/plugin-api/automations/{id}', ('id',)),
    ('DELETE', re.compile('^/automations/(?P<id>[^/]+)$'), '/plugin-api/automations/{id}', ('id',)),
    ('GET', re.compile('^/automations/runs/history$'), '/plugin-api/automations/runs/history', ()),
    ('PATCH', re.compile('^/workspaces/(?P<id>[^/]+)$'), '/plugin-api/workspaces/{id}', ('id',)),
    ('DELETE', re.compile('^/workspaces/(?P<id>[^/]+)$'), '/plugin-api/workspaces/{id}', ('id',)),
    ('POST', re.compile('^/docker/ssh/connect\\-totp$'), '/plugin-api/docker/ssh/connect-totp', ()),
    ('GET', re.compile('^/proxmox/discover/stream$'), '/plugin-api/proxmox/discover/stream', ()),
    ('PUT', re.compile('^/snippets/folders/rename$'), '/plugin-api/snippets/folders/rename', ()),
    ('PUT', re.compile('^/snippets/(?P<id>[^/]+)$'), '/plugin-api/snippets/{id}', ('id',)),
    ('DELETE', re.compile('^/snippets/(?P<id>[^/]+)$'), '/plugin-api/snippets/{id}', ('id',)),
    ('GET', re.compile('^/snippets/(?P<id>[^/]+)$'), '/plugin-api/snippets/{id}', ('id',)),
    ('POST', re.compile('^/docker/ssh/disconnect$'), '/plugin-api/docker/ssh/disconnect', ()),
    ('POST', re.compile('^/ssh/tunnel/disconnect$'), '/plugin-api/tunnels/disconnect', ()),
    ('PATCH', re.compile('^/fleets/(?P<id>[^/]+)$'), '/plugin-api/fleets/{id}', ('id',)),
    ('DELETE', re.compile('^/fleets/(?P<id>[^/]+)$'), '/plugin-api/fleets/{id}', ('id',)),
    ('POST', re.compile('^/docker/ssh/keepalive$'), '/plugin-api/docker/ssh/keepalive', ()),
    ('GET', re.compile('^/status/(?P<id>[^/]+)$'), '/host/status/{id}', ('id',)),
    ('GET', re.compile('^/vault/oidc/callback$'), '/plugin-api/vault/oidc/callback', ()),
    ('POST', re.compile('^/docker/ssh/connect$'), '/plugin-api/docker/ssh/connect', ()),
    ('POST', re.compile('^/ssh/tunnel/connect$'), '/plugin-api/tunnels/connect', ()),
    ('GET', re.compile('^/docker/ssh/status$'), '/plugin-api/docker/ssh/status', ()),
    ('POST', re.compile('^/ssh/tunnel/cancel$'), '/plugin-api/tunnels/cancel', ()),
    ('GET', re.compile('^/ssh/tunnel/status$'), '/plugin-api/tunnels/status', ()),
    ('POST', re.compile('^/ai/chat/stream$'), '/plugin-api/ai/chat/stream', ()),
    ('GET', re.compile('^/workspaces/last\\-session$'), '/plugin-api/workspaces/last-session', ()),
    ('PUT', re.compile('^/workspaces/last\\-session$'), '/plugin-api/workspaces/last-session', ()),
    ('POST', re.compile('^/session\\-sharing/create$'), '/plugin-api/session-sharing/create', ()),
    ('POST', re.compile('^/terminal/image\\-upload$'), '/plugin-api/ssh-terminal/image-upload', ()),
    ('POST', re.compile('^/snippets/bulk\\-import$'), '/plugin-api/snippets/bulk-import', ()),
    ('GET', re.compile('^/users/host\\-defaults$'), '/plugin-api/alerts/meta', ()),
    ('GET', re.compile('^/tailscale/devices$'), '/plugin-api/tailscale/devices', ()),
    ('POST', re.compile('^/tunnel/disconnect$'), '/plugin-api/tunnels/disconnect', ()),
    ('POST', re.compile('^/ai/probe\\-models$'), '/plugin-api/ai/probe-models', ()),
    ('GET', re.compile('^/ai/conversations$'), '/plugin-api/ai/conversations', ()),
    ('GET', re.compile('^/homepage/favicon$'), '/plugin-api/homepage/favicon', ()),
    ('POST', re.compile('^/proxmox/discover$'), '/plugin-api/proxmox/discover', ()),
    ('POST', re.compile('^/snippets/folders$'), '/plugin-api/snippets/folders', ()),
    ('GET', re.compile('^/snippets/folders$'), '/plugin-api/snippets/folders', ()),
    ('PUT', re.compile('^/snippets/reorder$'), '/plugin-api/snippets/reorder', ()),
    ('POST', re.compile('^/snippets/execute$'), '/plugin-api/snippets/execute', ()),
    ('GET', re.compile('^/homepage/layout$'), '/plugin-api/homepage/layout', ()),
    ('PUT', re.compile('^/homepage/layout$'), '/plugin-api/homepage/layout', ()),
    ('GET', re.compile('^/snippets/export$'), '/plugin-api/snippets/export', ()),
    ('GET', re.compile('^/activity/recent$'), '/plugin-api/homepage/items', ()),
    ('GET', re.compile('^/homepage/items$'), '/plugin-api/homepage/items', ()),
    ('POST', re.compile('^/homepage/items$'), '/plugin-api/homepage/items', ()),
    ('GET', re.compile('^/homepage/proxy$'), '/plugin-api/homepage/proxy', ()),
    ('GET', re.compile('^/vault/profiles$'), '/plugin-api/vault/profiles', ()),
    ('POST', re.compile('^/vault/profiles$'), '/plugin-api/vault/profiles', ()),
    ('POST', re.compile('^/tunnel/connect$'), '/plugin-api/tunnels/connect', ()),
    ('GET', re.compile('^/homepage/ping$'), '/plugin-api/homepage/ping', ()),
    ('GET', re.compile('^/termix\\-id/me$'), '/plugin-api/termix-identity/me', ()),
    ('POST', re.compile('^/ai/providers$'), '/plugin-api/ai/providers', ()),
    ('GET', re.compile('^/ai/providers$'), '/plugin-api/ai/providers', ()),
    ('GET', re.compile('^/homepage/rss$'), '/plugin-api/homepage/rss', ()),
    ('POST', re.compile('^/proxmox/sync$'), '/plugin-api/proxmox/sync', ()),
    ('GET', re.compile('^/ai/status$'), '/plugin-api/ai/status', ()),
    ('GET', re.compile('^/c2s\\-tunnel\\-presets$'), '/plugin-api/tunnels/presets', ()),
    ('POST', re.compile('^/network\\-topology$'), '/plugin-api/network-topology', ()),
    ('GET', re.compile('^/network\\-topology$'), '/plugin-api/network-topology', ()),
    ('POST', re.compile('^/secret\\-sources$'), '/plugin-api/secret-sources', ()),
    ('GET', re.compile('^/secret\\-sources$'), '/plugin-api/secret-sources', ()),
    ('GET', re.compile('^/service\\-links$'), '/plugin-api/homepage/service-links', ()),
    ('GET', re.compile('^/session_logs$'), '/plugin-api/session-recording', ()),
    ('GET', re.compile('^/alert\\-rules$'), '/plugin-api/alerts/rules', ()),
    ('POST', re.compile('^/alert\\-rules$'), '/plugin-api/alerts/rules', ()),
    ('GET', re.compile('^/automations$'), '/plugin-api/automations', ()),
    ('POST', re.compile('^/automations$'), '/plugin-api/automations', ()),
    ('POST', re.compile('^/workspaces$'), '/plugin-api/workspaces', ()),
    ('GET', re.compile('^/workspaces$'), '/plugin-api/workspaces', ()),
    ('POST', re.compile('^/snippets$'), '/plugin-api/snippets', ()),
    ('GET', re.compile('^/snippets$'), '/plugin-api/snippets', ()),
    ('POST', re.compile('^/fleets$'), '/plugin-api/fleets', ()),
    ('GET', re.compile('^/fleets$'), '/plugin-api/fleets', ()),
    ('GET', re.compile('^/status$'), '/host/status', ()),
    ('GET', re.compile('^/alerts$'), '/plugin-api/alerts/items', ()),
]


def rewrite_path(method: str, path: str) -> str:
    """Return the Termix 2.9 path for a legacy SDK path, or `path` unchanged."""
    for entry_method, pattern, template, names in _ENTRIES:
        if entry_method != method:
            continue
        match = pattern.match(path)
        if not match:
            continue
        if not names:
            return template
        out = template
        for name in names:
            out = out.replace("{" + name + "}", match.group(name))
        return out
    return path
